name: zip
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Zip job (the zipping is done on upload automatically)
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # upload the artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: SiMP-resources
          path: SiMP-resources/
